{% set name = "pyratbay" %}
{% set version = "2.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyratbay-{{ version }}.tar.gz
  sha256: eac31a683f5dff376324e762355b66dedf8cd302b1f88aa197faaf3e6186fa48

build:
  number: 0
  skip: true  # [win]
  skip: true  # [py<39]
  entry_points:
    - pbay = pyratbay.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - numpy
    - pip
    - python
    - setuptools
  run:
    - matplotlib-base >=3.9.2
    - mc3 >=3.2.0
    - numpy >=2.0.0
    - scipy >=1.16.0
    - chemcat >=0.3.12
    - h5py >=3.10.0
    - python

test:
  imports:
    - pyratbay
    - pytest >=3.9
    - mpi4py >=3.1.4

about:
  home: https://github.com/pcubillos/pyratbay
  summary: Python Radiative Transfer in a Bayesian Framework
  license: GPL-2.0-only
  license_file: LICENSE
  dev_url: https://github.com/pcubillos/pyratbay
  doc_url: https://pyratbay.readthedocs.io/en/latest/index.html

extra:
  recipe-maintainers:
    - pcubillos
