{% set name = "pyratbay" %}
{% set version = "1.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyratbay-{{ version }}.tar.gz
  sha256: 3023461bed067f5f9557da26468450c3b13b1ed0609dd9800bc133ebc20e2bc4

build:
  number: 0
  skip: true  # [win]
  skip: true  # [py<35]
  entry_points:
    - pbay = pyratbay.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - numpy
    - pip
    - python
  run:
    - matplotlib-base >=1.3.1
    - mc3 >=3.0.7
    - numpy >=1.8.1
    - python
    - scipy >=0.13.3
    - sympy >=0.7.6
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pyratbay

about:
  home: https://github.com/pcubillos/pyratbay
  summary: Python Radiative Transfer in a Bayesian Framework.
  license: GPL-2.0-or-later
  license_file: LICENSE
  dev_url: https://github.com/pcubillos/pyratbay
  doc_url: https://pyratbay.readthedocs.io/en/latest/index.html

extra:
  recipe-maintainers:
    - pcubillos
